<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKkEVkbV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKkEVkbV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKkEVkbV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKkEVkbV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKkEVkbV\App_KernelDevDebugContainer([
    'container.build_hash' => 'KkEVkbV',
    'container.build_id' => '352298b2',
    'container.build_time' => 1634252290,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKkEVkbV');
